### ISSUE TITLE
Activity bar error and cannot open TODO files, the embedded list is also empty

### ISSUE THREAD

**Issue by pixelpicosean** [fabiospampinato/vscode-todo-plus#137]
Here's the screen shot of the error 
![devtool-screenshot](https://cl.ly/64cab5b2a639/Image%2525202018-10-11%252520at%2525201.49.36%252520PM.png)

**Comment by bva999** [comment]
I have the same problem... Error : 


/C:/Users/user/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] [UriError]: Scheme is missing: {scheme: "", authority: "", path: "/c:/Users/user/Documents/Work/PMCG/TODO", query: "", fragment: ""}
t.log @ /C:/Users/user/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282
/C:/Users/user/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] Extension "currenttodos" activated!
/C:/Users/user/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2374 Error: Path must be a string. Received undefined
	at assertPath (path.js:28:11)
	at Object.dirname (path.js:728:5)
	at C:\Users\user\.vscode\extensions\fabiospampinato.vscode-todo-plus-4.8.2\out\extension.js:648:40863
	at Generator.throw (<anonymous>)
	at o (C:\Users\user\.vscode\extensions\fabiospampinato.vscode-todo-plus-4.8.2\out\extension.js:648:39780)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:188:7)
t.onDidNotificationChange @ /C:/Users/user/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2374
/C:/Users/user/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:282 [Extension Host] SPFx localization is now active!
/C:/Users/user/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1409   ERR r is not a constructor: TypeError: r is not a constructor
	at C:\Users\user\.vscode\extensions\fabiospampinato.vscode-todo-plus-4.8.2\out\extension.js:230:2422
	at c (C:\Users\user\.vscode\extensions\fabiospampinato.vscode-todo-plus-4.8.2\out\extension.js:230:2455)
	at b.d._watchWithFsEvents (C:\Users\user\.vscode\extensions\fabiospampinato.vscode-todo-plus-4.8.2\out\extension.js:230:4247)
	at b.<anonymous> (C:\Users\user\.vscode\extensions\fabiospampinato.vscode-todo-plus-4.8.2\out\extension.js:230:5870)
	at LOOP (fs.js:1757:14)
	at _combinedTickCallback (internal/process/next_tick.js:131:7)
	at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by fabiospampinato** [comment]
Are you both on Windows?

Is the extension overall working though (todo files are highlighted, embedded todos are found etc.)?

**Comment by fabiospampinato** [comment]
This should be fixed in v4.8.3, there was a type in webpack's configuration.

**Comment by pixelpicosean** [comment]
I am using macOS you can see from that screenshot, and the latest version still not work. Only embedded todos are highlighted, todo files outline is sometimes visible before the error occurs.

**Comment by fabiospampinato** [comment]
> I am using macOS you can see from that screenshot

Right.

> Only embedded todos are highlighted

Todo+ doesn't highlight embedded todos, maybe you're using Highlight or TODO Highlight for that?

I'll investigate this further, thanks.

**Comment by pixelpicosean** [comment]
I have `Highlight` installed and it works, but todo+ still gives me same error after the `Highlight` get uninstalled

**Comment by fabiospampinato** [comment]
Yeah I don't think there's a conflict here. It's a problem with one of our dependencies I think.

What version of VSC, Todo+ and macOS are you running?

**Comment by pixelpicosean** [comment]
VSC: 1.28.0
Todo+: 4.8.4
macOS: 10.13.6

**Comment by pixelpicosean** [comment]
There's a notification says "Path must be a string. Received undefined"

**Comment by bva999** [comment]
VCS: 1.28.1
Windows 10
ToDo+: 4.8.4

**Comment by Hyominn** [comment]
I have the same problem ：（
VCS: 1.28.1
Windows 10
ToDo+: 4.8.4

**Comment by fabiospampinato** [comment]
Should be fixed for good in v4.8.5, do you guys confirm that?

**Comment by pixelpicosean** [comment]
Embed list now works and no error is thrown, but the files list only prints top level titles.

**Comment by bva999** [comment]
Confirm! It's work now .
